on: push
jobs:
    fourth-job: 
       runs-on: ubuntu-latest
       steps: 
            - run: node --version
            - name: Checkout code
              uses: action/checkout@v2
            - run: npm --version
            - run: npm install
            - run: node index.js
            - name: Run tests
              run: npm run test 